import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `convex codegen`; committed but not ours to lint.
    "convex/_generated/**",
    // Third-party bundle copied in at build time by scripts/copy-kuromoji-dict.mjs.
    "public/kuromoji/**",
    // Built from a dependency at build time by scripts/build-webp-worker.mjs.
    "public/webp/**",
    // Copied in from a dependency at build time by scripts/copy-pdfjs.mjs.
    "public/pdfjs/**",
    // The desktop app: a package of its own, in Rust (docs/DESKTOP.md).
    "desktop/**",
  ]),
]);

export default eslintConfig;
